title: Sujin Park
author: Sujin Park
#email: your-email@domain.com
description: >
  2023. ⓒ All rights reserved

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
- publications.md
#- github.md

#footers:
- {title: Mail, icon: envelope, url: "mailto:racom02@g.skku.edu"}

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
