title: "Sujin Park"
author: ""
email: racom02@g.skku.edu
description: >
  2023. ⓒ All rights reserved
  
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
  - index.md
  - about.md
  - publications.md
  - search.html

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
