title: "Sujin Park"
author: ""
email: sup031@ucsd.edu
description: >
  Using the [Minima Reboot](http://jekyllthemes.org/themes/minima-reboot/) theme for Jekyll.
  
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
  - index.md
  - about.md
  - publications.md
  - posts.md

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
